# See https://pre-commit.com/ for usage and config
repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        files: '\.rs$'
        entry: cargo fmt -- --check --verbose

      - id: clippy
        name: clippy
        language: system
        files: '\.rs$'
        entry: cargo clippy --all-targets --all -- -D warnings
        pass_filenames: false

      - id: test
        name: cargo test
        description: Run tests with cargo test.
        entry: cargo test --
        language: rust
        types: [rust]
        stages: [push]
        args: []